// // This file is auto-generated by ./bin/rails stimulus:manifest:update
// // Run that command whenever you add a new controller or create them with
// // ./bin/rails generate stimulus controllerName

// import { application } from "./application"

// // Manually import each Stimulus controller
// import CommentFormController from "./comment_form_controller"
// application.register("comment-form", CommentFormController)

// import FlashController from "./flash_controller"
// application.register("flash", FlashController)

// import HamburgerController from "./hamburger_controller"
// application.register("hamburger", HamburgerController)

// import HelloController from "./hello_controller"
// application.register("hello", HelloController)

// import SortableController from "./sortable_controller"
// application.register("sortable", SortableController)